version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "basic-sam-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dimqp2mu66tr"
s3_prefix = "basic-sam-stack"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
