AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  basic-aws-api

  Sample SAM Template for basic-aws-api
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  BasicAWSApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionUri: ./swagger.yaml

  ListTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ListTasksFunction
      CodeUri: src/
      Handler: index.listTasks
      Runtime: nodejs16.x
      Policies:
        DynamoDBReadPolicy:
          TableName:
            Ref: TasksTable
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId:
              Ref: BasicAWSApiGateway
            Path: /
            Method: GET
  TasksTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: TasksTable
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      

Outputs:
 BasicAWSApiGateway:
    Value: !Sub "https://${BasicAWSApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev/"

